-- Migration 9: Seed Jurisdictions Data
-- Context Module - Database Schema & RLS (Supabase)

-- Seed EU/EEA jurisdictions with GDPR adequacy status
INSERT INTO jurisdictions (country_code, name_en, name_sk, gdpr_adequacy, supervisory_authority) VALUES
-- EU Member States (all have GDPR adequacy by definition)
('AT', 'Austria', 'Rakúsko', true, 'Austrian Data Protection Authority (DSB)'),
('BE', 'Belgium', 'Belgicko', true, 'Belgian Data Protection Authority'),
('BG', 'Bulgaria', 'Bulharsko', true, 'Commission for Personal Data Protection'),
('HR', 'Croatia', 'Chorvátsko', true, 'Croatian Personal Data Protection Agency'),
('CY', 'Cyprus', 'Cyprus', true, 'Office of the Commissioner for Personal Data Protection'),
('CZ', 'Czech Republic', 'Česká republika', true, 'Office for Personal Data Protection'),
('DK', 'Denmark', 'Dánsko', true, 'Danish Data Protection Agency'),
('EE', 'Estonia', 'Estónsko', true, 'Estonian Data Protection Inspectorate'),
('FI', 'Finland', 'Fínsko', true, 'Office of the Data Protection Ombudsman'),
('FR', 'France', 'Francúzsko', true, 'Commission Nationale de l''Informatique et des Libertés (CNIL)'),
('DE', 'Germany', 'Nemecko', true, 'Federal Commissioner for Data Protection and Freedom of Information'),
('GR', 'Greece', 'Grécko', true, 'Hellenic Data Protection Authority'),
('HU', 'Hungary', 'Maďarsko', true, 'National Authority for Data Protection and Freedom of Information'),
('IE', 'Ireland', 'Írsko', true, 'Data Protection Commission'),
('IT', 'Italy', 'Taliansko', true, 'Italian Data Protection Authority (Garante)'),
('LV', 'Latvia', 'Lotyšsko', true, 'Data State Inspectorate'),
('LT', 'Lithuania', 'Litva', true, 'State Data Protection Inspectorate'),
('LU', 'Luxembourg', 'Luxembursko', true, 'National Commission for Data Protection (CNPD)'),
('MT', 'Malta', 'Malta', true, 'Office of the Information and Data Protection Commissioner'),
('NL', 'Netherlands', 'Holandsko', true, 'Dutch Data Protection Authority (AP)'),
('PL', 'Poland', 'Poľsko', true, 'Personal Data Protection Office'),
('PT', 'Portugal', 'Portugalsko', true, 'National Data Protection Commission (CNPD)'),
('RO', 'Romania', 'Rumunsko', true, 'National Supervisory Authority for Personal Data Processing'),
('SK', 'Slovakia', 'Slovensko', true, 'Office for Personal Data Protection of the Slovak Republic'),
('SI', 'Slovenia', 'Slovinsko', true, 'Information Commissioner'),
('ES', 'Spain', 'Španielsko', true, 'Spanish Data Protection Agency (AEPD)'),
('SE', 'Sweden', 'Švédsko', true, 'Swedish Authority for Privacy Protection (IMY)'),

-- EEA Countries (not EU but have GDPR adequacy)
('IS', 'Iceland', 'Island', true, 'Icelandic Data Protection Authority'),
('LI', 'Liechtenstein', 'Lichtenštajnsko', true, 'Data Protection Office'),
('NO', 'Norway', 'Nórsko', true, 'Norwegian Data Protection Authority'),

-- Countries with EU Adequacy Decisions (as of 2024)
('AD', 'Andorra', 'Andorra', true, 'Andorran Data Protection Agency'),
('AR', 'Argentina', 'Argentína', true, 'Argentine Data Protection Authority'),
('CA', 'Canada', 'Kanada', true, 'Office of the Privacy Commissioner of Canada'),
('FO', 'Faroe Islands', 'Faerské ostrovy', true, null),
('GG', 'Guernsey', 'Guernsey', true, 'Office of the Data Protection Commissioner'),
('IL', 'Israel', 'Izrael', true, 'Israel Privacy Protection Authority'),
('IM', 'Isle of Man', 'Ostrov Man', true, 'Isle of Man Information Commissioner'),
('JP', 'Japan', 'Japonsko', true, 'Personal Information Protection Commission'),
('JE', 'Jersey', 'Jersey', true, 'Jersey Office of the Information Commissioner'),
('NZ', 'New Zealand', 'Nový Zéland', true, 'Privacy Commissioner'),
('CH', 'Switzerland', 'Švajčiarsko', true, 'Federal Data Protection and Information Commissioner'),
('UY', 'Uruguay', 'Uruguaj', true, 'Data Protection Unit'),
('GB', 'United Kingdom', 'Spojené kráľovstvo', true, 'Information Commissioner''s Office (ICO)'),

-- Major countries without adequacy decisions
('US', 'United States', 'Spojené štáty', false, 'Federal Trade Commission'),
('CN', 'China', 'Čína', false, 'Cyberspace Administration of China'),
('IN', 'India', 'India', false, null),
('BR', 'Brazil', 'Brazília', false, 'National Data Protection Authority (ANPD)'),
('RU', 'Russia', 'Rusko', false, 'Federal Service for Supervision of Communications'),
('AU', 'Australia', 'Austrália', false, 'Office of the Australian Information Commissioner'),
('KR', 'South Korea', 'Južná Kórea', false, 'Personal Information Protection Commission'),
('MX', 'Mexico', 'Mexiko', false, 'National Institute for Transparency'),
('ZA', 'South Africa', 'Južná Afrika', false, 'Information Regulator South Africa'),
('TR', 'Turkey', 'Turecko', false, 'Personal Data Protection Authority'),
('TH', 'Thailand', 'Thajsko', false, 'Personal Data Protection Committee'),
('SG', 'Singapore', 'Singapur', false, 'Personal Data Protection Commission'),
('MY', 'Malaysia', 'Malajzia', false, 'Personal Data Protection Department'),
('ID', 'Indonesia', 'Indonézia', false, null),
('PH', 'Philippines', 'Filipíny', false, 'National Privacy Commission'),
('VN', 'Vietnam', 'Vietnam', false, null),
('EG', 'Egypt', 'Egypt', false, null),
('NG', 'Nigeria', 'Nigéria', false, 'Nigeria Data Protection Commission'),
('KE', 'Kenya', 'Keňa', false, 'Office of the Data Protection Commissioner'),
('GH', 'Ghana', 'Ghana', false, 'Data Protection Commission'),
('MA', 'Morocco', 'Maroko', false, 'National Commission for the Control of Personal Data Protection'),
('TN', 'Tunisia', 'Tunisko', false, 'National Authority for the Protection of Personal Data'),

-- Other notable jurisdictions
('HK', 'Hong Kong', 'Hong Kong', false, 'Office of the Privacy Commissioner for Personal Data'),
('TW', 'Taiwan', 'Taiwan', false, 'National Development Council'),
('AE', 'United Arab Emirates', 'Spojené arabské emiráty', false, 'UAE Data Office'),
('SA', 'Saudi Arabia', 'Saudská Arábia', false, 'Saudi Data and Artificial Intelligence Authority'),
('QA', 'Qatar', 'Katar', false, null),
('KW', 'Kuwait', 'Kuvajt', false, null),
('BH', 'Bahrain', 'Bahrajn', false, null),
('OM', 'Oman', 'Omán', false, null),
('JO', 'Jordan', 'Jordánsko', false, null),
('LB', 'Lebanon', 'Libanon', false, null),
('IR', 'Iran', 'Irán', false, null),
('IQ', 'Iraq', 'Irak', false, null),
('AF', 'Afghanistan', 'Afganistan', false, null),
('PK', 'Pakistan', 'Pakistan', false, null),
('BD', 'Bangladesh', 'Bangladéš', false, null),
('LK', 'Sri Lanka', 'Srí Lanka', false, null),
('MM', 'Myanmar', 'Mjanmarsko', false, null),
('KH', 'Cambodia', 'Kambodža', false, null),
('LA', 'Laos', 'Laos', false, null),
('NP', 'Nepal', 'Nepál', false, null),
('BT', 'Bhutan', 'Bhután', false, null),
('MV', 'Maldives', 'Maldivy', false, null),
('CL', 'Chile', 'Čile', false, 'Personal Data Protection Agency'),
('PE', 'Peru', 'Peru', false, 'National Authority for Personal Data Protection'),
('CO', 'Colombia', 'Kolumbia', false, 'Superintendency of Industry and Commerce'),
('VE', 'Venezuela', 'Venezuela', false, null),
('EC', 'Ecuador', 'Ekvádor', false, null),
('BO', 'Bolivia', 'Bolívia', false, null),
('PY', 'Paraguay', 'Paraguaj', false, null),
('GY', 'Guyana', 'Guyana', false, null),
('SR', 'Suriname', 'Surinam', false, null),
('UZ', 'Uzbekistan', 'Uzbekistan', false, null),
('KZ', 'Kazakhstan', 'Kazachstan', false, null),
('KG', 'Kyrgyzstan', 'Kirgizstan', false, null),
('TJ', 'Tajikistan', 'Tadžikistan', false, null),
('TM', 'Turkmenistan', 'Turkménistan', false, null),
('MN', 'Mongolia', 'Mongolsko', false, null),
('GE', 'Georgia', 'Gruzínsko', false, 'Personal Data Protection Inspector'),
('AM', 'Armenia', 'Arménsko', false, null),
('AZ', 'Azerbaijan', 'Azerbajdžan', false, null),
('BY', 'Belarus', 'Bielorusko', false, null),
('UA', 'Ukraine', 'Ukrajina', false, 'Ukrainian Parliament Commissioner for Human Rights'),
('MD', 'Moldova', 'Moldavsko', false, 'National Center for Personal Data Protection'),
('AL', 'Albania', 'Albánsko', false, 'Commissioner for the Right to Information and Personal Data Protection'),
('BA', 'Bosnia and Herzegovina', 'Bosna a Hercegovina', false, 'Personal Data Protection Agency'),
('ME', 'Montenegro', 'Čierna Hora', false, 'Agency for Personal Data Protection and Free Access to Information'),
('MK', 'North Macedonia', 'Severné Macedónsko', false, 'Agency for Personal Data Protection'),
('RS', 'Serbia', 'Srbsko', false, 'Commissioner for Information of Public Importance and Personal Data Protection'),
('XK', 'Kosovo', 'Kosovo', false, 'Information and Privacy Agency')
ON CONFLICT (country_code) DO NOTHING;